Vaskivskyi/ha-asusrouter

custom_components/asusrouter/translations/pt-BR.json

Pleasen, Add Brazilian Portuguese Translation!

Add Brazilian Portuguese Translation

---

README.md

Add credits to the readme as per #10

Add credits to HA AsusWRT and ollo69/ha_asuswrt_custom

---

README.md

Add info on missing WAN sensors for some devices [issue #30]

---

custom_components/asusrouter/bridge.py
custom_components/asusrouter/config_flow.py
custom_components/asusrouter/const.py
custom_components/asusrouter/strings.json
custom_components/asusrouter/translations/en.json

1. Device discovery
a. Fields: `Hostname`
b. If device found -> 2
2. Credentials (simplified setup)
a. Fields: `Username`, `Password`, `SSL usage`
b. If the device can be accessed with only this data -> 4, if not -> 3
3. Complete setup (more settings)
a. Fields: `Username`, `Password`, `Port`, `SSL usage`, `SSL check`, `Certificate path`
b. If the device can be accessed -> 4
4. Operation mode
a. Fields: `Enable monitor`, `Enable control`
b. -> 5
5. Interfaces to monitor
6. Device rename

Simplify config flow

---

custom_components/asusrouter/bridge.py
custom_components/asusrouter/const.py
custom_components/asusrouter/sensor.py

With attributes:
- `Type`
- `Gateway`
- `Mask`
- `DNS`
- `Private subnet`

New `wan_ip` sensor

---

custom_components/asusrouter/config_flow.py
custom_components/asusrouter/const.py
custom_components/asusrouter/router.py
custom_components/asusrouter/strings.json
custom_components/asusrouter/translations/en.json

This will help with #49 on the next release

Select `cache_time`, `scan_interval` and `consider_home` manually

---

custom_components/asusrouter/const.py
custom_components/asusrouter/dataclass.py
custom_components/asusrouter/light.py

`enable_control` should be `True` for the feature to work

Add LED control as `light` entity

---

custom_components/asusrouter/translations/pt-BR.json

Please, Add New Brazilian Portuguese Translation!

Add New Brazilian Portuguese Translation

---

README.md

Add RT-AX55 (instead of https://github.com/Vaskivskyi/ha-asusrouter/pull/96)

Update device compatibility list

---

README.md

Add `RT-AX82U` in the supported list

---

README.md

Add `Netgear R7000` (Merlin) to the supported list

---

README.md

Add `DSL-AC68U` to the supported list

---

custom_components/asusrouter/manifest.json

Bump asusrouter to 0.6.3

---

hacs.json

Bump HomeAssistant to 2022.5.0

---

README.md

Add RT-AX86S to the supported list

---

README.md

Add `TUF-AX5400` to the supported list

---

README.md

Add `DSL-AX82U` to supported list

---

README.md

Add info on FW 5.x.x

---

README.md

Add `RT-AC51U` to the supported list

---

custom_components/asusrouter/const.py
custom_components/asusrouter/router.py
custom_components/asusrouter/sensor.py

Add device list as an attribute of `connected_devices` sensor

---

custom_components/asusrouter/bridge.py
custom_components/asusrouter/router.py
custom_components/asusrouter/services.yaml

Add `Reboot` service

---

README.md

Add `Netgear R6300V2` to the supported list

---

custom_components/asusrouter/translations/es-ES.json

Added Spanish (Spain) translation

feat() Add Spanish (Spain) translation

---

README.md

Add `RT-ACRH17` to the supported list

---

custom_components/asusrouter/manifest.json

Bump asusrouter to 0.9.2

---

custom_components/asusrouter/router.py

Switch `devices` attribute of `Connected devices` to list of dicts

---

README.md

Add the AiMesh implementation suggestions from #261

Update the development status

---

custom_components/asusrouter/binary_sensor.py
custom_components/asusrouter/bridge.py
custom_components/asusrouter/compilers.py
custom_components/asusrouter/const.py
custom_components/asusrouter/dataclass.py
custom_components/asusrouter/entity.py
custom_components/asusrouter/router.py
custom_components/asusrouter/services.yaml
custom_components/asusrouter/switch.py

Closes #213
Requires https://github.com/Vaskivskyi/asusrouter/pull/134 to be released

Add Guest WLAN support

---

custom_components/asusrouter/button.py
custom_components/asusrouter/const.py
custom_components/asusrouter/dataclass.py
custom_components/asusrouter/entity.py

Add `reboot` button

---

custom_components/asusrouter/binary_sensor.py
custom_components/asusrouter/bridge.py
custom_components/asusrouter/compilers.py
custom_components/asusrouter/const.py
custom_components/asusrouter/switch.py

Add OpenVPN Server support

---

custom_components/asusrouter/translations/es.json

feat(translations) Update spanish translations
feat(translations) Rename es-ES.json to es.json file to work properly

Update spanish translations

---

custom_components/asusrouter/manifest.json

Bump asusrouter to 0.12.0

---

custom_components/asusrouter/manifest.json

Bump asusrouter to 0.12.1

---

custom_components/asusrouter/translations/sk.json

I did the translation according to the instructions at https://community.home-assistant.io/t/custom-component-asusrouter-integration/416111/279

New Slovak language - sk.json

---

custom_components/asusrouter/translations/nl.json

Add Dutch translation

---

custom_components/asusrouter/device_tracker.py
custom_components/asusrouter/router.py

Improve device trackers unique ID

---

custom_components/asusrouter/bridge.py
custom_components/asusrouter/const.py

Adds feature requested in #464

Add secondary WAN info

---

custom_components/asusrouter/switch.py

Requires https://github.com/Vaskivskyi/asusrouter/pull/250 to be released

Fix bug with VPN switches

---

custom_components/asusrouter/__init__.py

Fixed typo in __init__.py

---

info.md

Fixed typo in info.md

---

custom_components/asusrouter/__init__.py

Fix warning on HA 2023.2.x

---

custom_components/asusrouter/bridge.py
custom_components/asusrouter/const.py
custom_components/asusrouter/router.py
custom_components/asusrouter/services.yaml

Requires https://github.com/Vaskivskyi/asusrouter/pull/272 to be released

Add `Port forwarding` features

---

custom_components/asusrouter/const.py
custom_components/asusrouter/router.py

Add `Media bridge` mode

---

custom_components/asusrouter/bridge.py
custom_components/asusrouter/const.py

Requires https://github.com/Vaskivskyi/asusrouter/pull/277 to be released to improve USB status

Add Port Status sensors

---

custom_components/asusrouter/translations/ru.json

Added basic ru translation. Can be uploaded to Inlang if it's gonna be used. Also can be updated in the future.

Add ru translation

---

custom_components/asusrouter/const.py

Requires HA to release PR 87792

Use EntityCategory from homeassistant.core

---

custom_components/asusrouter/compilers.py
custom_components/asusrouter/config_flow.py
custom_components/asusrouter/const.py
custom_components/asusrouter/sensor.py

Add HA unit conversion (traffic/speed)

---

README.md

Add `TUF-AX3000 V2` to the supported

---

custom_components/asusrouter/client.py
custom_components/asusrouter/helpers.py
custom_components/asusrouter/router.py

https://github.com/Vaskivskyi/ha-asusrouter/issues/570#issuecomment-1786133353

Remove orphaned attributes from disconnected clients

---

custom_components/asusrouter/bridge.py

Fix bug when no PF or PC rules set

---

custom_components/asusrouter/router.py

Fix issue with an empty `latest_connected` list

---

custom_components/asusrouter/bridge.py
custom_components/asusrouter/const.py
custom_components/asusrouter/helpers.py

Add OpenVPN client support for stock 388 FW

---

README.md

Update supported devices list

---

custom_components/asusrouter/client.py

Fix issue with clients data mix

---

custom_components/asusrouter/bridge.py
custom_components/asusrouter/router.py

Check that parental control rules are valid before saving them

---

custom_components/asusrouter/config_flow.py

Remove blank option from the configure menu

---

custom_components/asusrouter/router.py

Check that capabilities of the device tracker exist before accessing

---

custom_components/asusrouter/light.py

To fulfil HA 2024.3 requirements
#807

Add `color_mode` property for LED entity

---

custom_components/asusrouter/const.py

https://github.com/Vaskivskyi/ha-asusrouter/issues/793

Add `reboot_aimesh` button

---

custom_components/asusrouter/const.py
custom_components/asusrouter/router.py

Add guest network connected devices number

Add GuestNetwork Connected numbers sensor entity #790

---

custom_components/asusrouter/bridge.py
custom_components/asusrouter/const.py
custom_components/asusrouter/light.py
custom_components/asusrouter/modules/__init__.py
custom_components/asusrouter/modules/aura.py

Add Aura support

---

custom_components/asusrouter/bridge.py
custom_components/asusrouter/const.py
custom_components/asusrouter/modules/firmware.py
custom_components/asusrouter/update.py

Fixes #826 
Fixes #820
Fixes #813
Fixes #732

Switch to the new Firmware backend module

---

custom_components/asusrouter/client.py

Add identity attributes when adevice is disconnected (including in the `asusrouter_device_disconnected` event):
- `guest` binary flag
- `guest_id` integer number
Replace the `connection_type` attribute with the last known instead of `disconnected`
Closes #843

Rebuild client identity dictionary when disconnected

---

custom_components/asusrouter/device_tracker.py
custom_components/asusrouter/switch.py

Match `secondary` device type when creating clients

---

custom_components/asusrouter/entity.py

Improve logging on exceptions when creating an entity

---

custom_components/asusrouter/bridge.py

To have it compatible with the new `asusrouter.connection.Connection` (https://github.com/Vaskivskyi/asusrouter/pull/571/)

Don't verify SSL as default

---

custom_components/asusrouter/bridge.py

https://github.com/Vaskivskyi/asusrouter/pull/605

Switch to the new format for backend `ARConfig`
